/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeguimientoRouteImport } from './routes/seguimiento'
import { Route as PagoRouteImport } from './routes/pago'
import { Route as NumerosRouteImport } from './routes/numeros'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SeguimientoRoute = SeguimientoRouteImport.update({
  id: '/seguimiento',
  path: '/seguimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoRoute = PagoRouteImport.update({
  id: '/pago',
  path: '/pago',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerosRoute = NumerosRouteImport.update({
  id: '/numeros',
  path: '/numeros',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/numeros': typeof NumerosRoute
  '/pago': typeof PagoRoute
  '/seguimiento': typeof SeguimientoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/numeros': typeof NumerosRoute
  '/pago': typeof PagoRoute
  '/seguimiento': typeof SeguimientoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/numeros': typeof NumerosRoute
  '/pago': typeof PagoRoute
  '/seguimiento': typeof SeguimientoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/numeros' | '/pago' | '/seguimiento'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/numeros' | '/pago' | '/seguimiento'
  id: '__root__' | '/' | '/admin' | '/numeros' | '/pago' | '/seguimiento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  NumerosRoute: typeof NumerosRoute
  PagoRoute: typeof PagoRoute
  SeguimientoRoute: typeof SeguimientoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seguimiento': {
      id: '/seguimiento'
      path: '/seguimiento'
      fullPath: '/seguimiento'
      preLoaderRoute: typeof SeguimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago': {
      id: '/pago'
      path: '/pago'
      fullPath: '/pago'
      preLoaderRoute: typeof PagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numeros': {
      id: '/numeros'
      path: '/numeros'
      fullPath: '/numeros'
      preLoaderRoute: typeof NumerosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  NumerosRoute: NumerosRoute,
  PagoRoute: PagoRoute,
  SeguimientoRoute: SeguimientoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
